name: Pull Request
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      ##########################################################################
      # Setup environment.
      ##########################################################################

      - uses: actions/checkout@v3

      - run: curl https://storage.googleapis.com/stored-stuff/wallet-adapter.tar.gz | tar -xz -C wallet-adapter

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - run: yarn install

      ##########################################################################
      # Yarn test.
      ##########################################################################

      - run: yarn test

      - name: "[e2e] build extension"
        env:
          CI: "" # so that build warnings aren't treated like errors (for now)
        run: yarn build

      ##########################################################################
      # Release.
      ##########################################################################

      #
      # TODO: the master branch conditionson all these are bit hacky. Probably
      #       a cleaner way of doing this.
      #

      - name: "zip build artifacts"
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        working-directory: packages/app-extension
        run: zip -r build.zip build/
      - name: "upload build artifacts"
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          name: backpack-build
          path: packages/app-extension/build.zip
      - uses: actions/download-artifact@v2
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          name: backpack-build
          path: ./
      - uses: actions/create-release@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        name: Create Draft Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest-${{ github.run_number }}
          release_name: latest-${{ github.run_number }}
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1.0.1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build.zip
          asset_name: build.zip
          asset_content_type: application/zip
