name: Pull Request
on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
  push:
    branches:
      - master

env:
  solana_version: 1.10.32
  build_version_number: ${{ github.run_number }}
  full_semver_version: 0.0.5-latest.${{ github.run_number }}

jobs:
  add-labels-based-on-whats-changed:
    name: Add PR labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            mobile:
              - 'packages/app-mobile/**'
            extension:
              - 'packages/app-extension/**'
            xnft:
              - 'packages/react-xnft/**'
              - 'packages/react-xnft-renderer/**'
              - 'packages/xnft/**'
              - 'packages/xnft-cli/**'

      - if: steps.changes.outputs.mobile == 'true'
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "mobile"

      - if: steps.changes.outputs.extension == 'true'
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "extension"

      - if: steps.changes.outputs.xnft == 'true'
        uses: andymckay/labeler@1.0.4
        with:
          add-labels: "xnft"

  tests:
    runs-on: ubuntu-latest
    name: Build and run tests
    # https://turborepo.org/docs/ci/github-actions
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      ##########################################################################
      # Setup environment.
      ##########################################################################

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: actions/cache@v3
        name: yarn-cache
        id: yarn-cache
        with:
          path: |
            **/node_modules
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            !**/node_modules/.cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn

      ##########################################################################
      # Yarn install.
      ##########################################################################

      - name: yarn install
        run: yarn install --frozen-lockfile --prefer-offline

      ##########################################################################
      # Yarn test.
      ##########################################################################

      - run: yarn test

      - name: "[solana] cache"
        uses: actions/cache@v3
        id: cache-solana
        with:
          path: |
            ~/.cache/solana/
            ~/.local/share/solana/
          key: solana-${{ runner.os }}-${{ env.solana_version }}
      - name: "[solana] install solana"
        if: steps.cache-solana.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config build-essential libudev-dev
          sh -c "$(curl -sSfL https://release.solana.com/v${{ env.solana_version }}/install)"
      - name: "[solana] add to PATH"
        run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      # https://playwright.dev/docs/next/ci#running-headed
      - name: "[e2e tests] run playwright tests on extension"
        run: xvfb-run yarn e2e

      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: playwright-report
          path: packages/app-extension/playwright-report/
          retention-days: 1

      ##########################################################################
      # Build extension.
      ##########################################################################

      #
      # Rebuild the extension with an explicit config.
      #
      - name: "build for release"
        env:
          BACKPACK_CONFIG_VERSION: "latest-${{ github.run_number }}"
          BACKPACK_CONFIG_LOG_LEVEL: "info"
          BACKPACK_FEATURE_LIGHT_MODE: "true"
          BACKPACK_FEATURE_POP_MODE: "true"
          # CI!=true so that build warnings aren't treated like errors (for now)
          CI: ""
        run: yarn build

      #
      # Rebuild the extension with an explicitly tagged version.
      #
      - name: "tag build version"
        run: pushd ./packages/app-extension && ./scripts/version.sh latest-${{ github.run_number }} && popd
      - name: "build extension for release"
        # CI!=true so that build warnings aren't treated like errors (for now)
        env:
          CI: ""
        working-directory: packages/app-extension
        run: VERSION_NUMBER="${{ env.full_semver_version }}" yarn build:release

      ##########################################################################
      # GitHub Pages.
      ##########################################################################

      - run: cd packages/background && yarn build:html

      - if: github.event_name == 'pull_request'
        name: "set env.commit_sha from latest commit in PR"
        run: echo "commit_sha=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
      - if: github.event_name == 'push'
        name: "set env.commit_sha from commit or merge commit"
        run: echo "commit_sha=${{ github.sha }}" >> $GITHUB_ENV

      - name: "set env.short_sha"
        run: echo "short_sha=`echo "${{ env.commit_sha }}" | cut -c1-8`" >> $GITHUB_ENV

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: packages/background/build
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_dir: "background-scripts/${{ env.short_sha }}"

      - name: "Deploy ledger injection"
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: packages/ledger-injection/dist
          deploy_key: ${{ secrets.LEDGER_INJECTION_DEPLOY_KEY }}
          external_repository: coral-xyz/ledger-injection

      ##########################################################################
      # Upload build artifacts.
      ##########################################################################

      - name: "zip build artifacts"
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        working-directory: packages/app-extension
        run: zip -r build-${{ github.run_number }}.zip build/

      - name: "upload build artifacts"
        # if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: backpack-build
          path: packages/app-extension/build-${{ github.run_number }}.zip

      ##########################################################################
      # Release.
      ##########################################################################

      #
      # TODO: the master branch conditionson all these are bit hacky. Probably
      #       a cleaner way of doing this.
      #

      - uses: actions/download-artifact@v3
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          name: backpack-build
          path: ./

      - uses: actions/create-release@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        name: Create Draft Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest-${{ github.run_number }}
          release_name: latest-${{ github.run_number }}
          draft: false
          prerelease: false

      - uses: actions/upload-release-asset@v1.0.1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build-${{ github.run_number }}.zip
          asset_name: build-${{ github.run_number }}.zip
          asset_content_type: application/zip

      ##########################################################################
      # Send artifacts to out channels.
      ##########################################################################

      - name: "post artifacts to Discord"
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: sinshutu/upload-to-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: packages/app-extension/build-${{ github.run_number }}.zip

      ##########################################################################
      # NPM Publish.
      ##########################################################################

      - name: "update npm package version"
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: ./scripts/npm_release.sh 0.1.0-latest.${{ github.run_number }}
      - name: "publish to npm: common-public"
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
          tag: latest
          package: packages/common-public/package.json
      - name: "publish to npm: themes"
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
          tag: latest
          package: packages/themes/package.json
      - name: "publish to npm: react-xnft"
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
          tag: latest
          package: packages/react-xnft/package.json
      - name: "publish to npm: xnft-cli"
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
          tag: latest
          package: packages/xnft-cli/package.json
